In [95]:
import numpy as np

In [96]:
a = np.array([[1, 2, 1],
              [-2, 1, 1]])

b = np.array([[3, 1],
              [-1, 0],
              [2, 4]])

c = np.array([[-2, 2],
              [1, -1],
              [1, 2]])

#TASK 1:
*Выполнить операции над матрицами: <br>
1) A+2*B <br>
*2) B+2*C

In [97]:
'''A+2*B'''
b2 = np.dot(2, b)
try:
    print(a + b2)
except ValueError:
    print('A+2*B:\nFold the Matrix of different sizes is prohibited')

A+2*B:
Fold the Matrix of different sizes is prohibited


In [98]:
'''B+2*C'''
c2 = np.dot(2, c)
try:
    print('B+2C:\n', b + c2)
except ValueError:
    print('B+2*C: fold the Matrix of different sizes is prohibited')

B+2C:
 [[-1  5]
 [ 1 -2]
 [ 4  8]]


#TASK 2:
*Создать матрицу размером 8х8 элементов, состоящую из нулей.Заполнить эту матрицу значениями, расположенными в шахматном порядке.Задачу решить через срезы массива NumPy(должно получиться буквально двумя командами).*

In [99]:
zero_matrix = np.zeros((8, 8), dtype=int)
zero_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [100]:
zero_matrix[1::2, ::2] = 1
zero_matrix[::2, 1::2] = 1
zero_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#TASK 3:
*1) Сформировать два вектора:
первый длиной 15 элементов со значениями от 0 до 1,4 с шагом 0,1;второй–длиной 6 элементов со значениями от 1 до 6.*

In [101]:
arr1 = np.arange(start=0, stop=1.5, step=0.1, dtype=float)
arr2 = np.linspace(1, 6, 6, dtype=int)

In [102]:
arr1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4])

In [103]:
arr2

array([1, 2, 3, 4, 5, 6])

*2) Преобразовать первый вектор в матрицу 5х3, а второй – в матрицу 3х2. Выполнить перемножение этих матриц. Сами матрицы и результат их перемножения вывести на экран.*

In [104]:
reshaped_arr1 = arr1.reshape((5, 3))
reshaped_arr1

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8],
       [0.9, 1. , 1.1],
       [1.2, 1.3, 1.4]])

In [105]:
reshaped_arr2 = arr2.reshape((3, 2))
reshaped_arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
result_multi = np.dot(reshaped_arr1, reshaped_arr2)
result_multi

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

#TASK 4:
*1) Сформировать вектор из целых чисел (тип элементов должен быть int32) размерностью 36 и значениями 1,3,5,7,...и так далее:*

In [107]:
arr = np.linspace(1, 36, 35, dtype=int)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       36])

*2) Выделить из этого вектора все элементы со значениями кратными:*

In [108]:
new_array = np.array([], dtype=int)
for i in arr:
    if i % 3 == 0:
        new_array = np.append(new_array, i)
    else:
        pass

*3) Вывести результат на экран (исходный вектор и с кратными числами):*

In [109]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       36])

In [110]:
new_array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])